name: Unit Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter (master channel)
        uses: subosito/flutter-action@v2
        with:
          channel: master
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Run analyzer
        run: flutter analyze --no-pub

      - name: Run unit tests
        run: flutter test --no-pub --reporter expanded

      - name: Upload coverage (artifact)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
          if-no-files-found: ignore
